%{
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <ctype.h>
#include <getopt.h>

extern int yylex(void);
extern int yyparse(void);
void yyerror(const char *s);

// Dynamic string buffer for arbitrary length payloads
typedef struct {
    char *data;
    size_t len;
    size_t cap;
} StringBuffer;

static StringBuffer g_text_buf = {NULL, 0, 0};
static char g_table_name[64] = "raw_corpus";
static char g_doc_id[128] = "anon_doc";
static char g_lang[32] = "ja";
static char g_category[64] = "general";

static char g_default_doc_id[128] = "anon_doc";
static char g_default_lang[32] = "ja";
static char g_default_category[64] = "general";

// Configurable column names
static char g_col_doc_id[64] = "doc_id";
static char g_col_lang[64] = "lang";
static char g_col_category[64] = "category";
static char g_col_raw_text[64] = "raw_text";
static char g_col_created_at[64] = "created_at";

// Column inclusion flags (default all included)
static bool g_has_doc_id = true;
static bool g_has_lang = true;
static bool g_has_category = true;
static bool g_has_raw_text = true;
static bool g_has_created_at = true;

static long g_insert_count = 0;
static long g_batch_size = 1000;
static bool g_whole_mode = false;

static void buf_init(StringBuffer *b) {
    b->len = 0;
    b->cap = 256;
    b->data = (char *)malloc(b->cap);
    if (!b->data) {
        fprintf(stderr, "Fatal: Out of memory\n");
        exit(1);
    }
    b->data[0] = '\0';
}

static void buf_append_char(StringBuffer *b, char c) {
    if (b->len + 2 > b->cap) {
        b->cap = (b->cap < 1024) ? b->cap * 2 : b->cap + 4096;
        b->data = (char *)realloc(b->data, b->cap);
        if (!b->data) {
            fprintf(stderr, "Fatal: Out of memory\n");
            exit(1);
        }
    }
    b->data[b->len++] = c;
    b->data[b->len] = '\0';
}

static void buf_free(StringBuffer *b) {
    if (b->data) {
        free(b->data);
        b->data = NULL;
    }
    b->len = 0;
    b->cap = 0;
}

// Safely escape SQL string literal (' -> '') and sanitize binary/control characters
static void print_escaped_literal(const char *src) {
    putchar('\'');
    if (src) {
        for (const unsigned char *p = (const unsigned char *)src; *p; p++) {
            if (*p == '\'') {
                putchar('\'');
                putchar('\'');
            } else if (*p == '\0') {
                continue;
            } else if (*p < 0x20 && *p != '\n' && *p != '\r' && *p != '\t') {
                putchar(' ');
            } else {
                putchar(*p);
            }
        }
    }
    putchar('\'');
}

// Clean and sanitize string copying into target buffer
static void sanitize_string_copy(char *dst, const char *src, size_t max_len) {
    if (!dst || max_len == 0) return;
    if (!src) {
        dst[0] = '\0';
        return;
    }

    size_t d_idx = 0;
    for (const unsigned char *p = (const unsigned char *)src; *p && d_idx + 1 < max_len; p++) {
        if (*p == '\0') {
            continue;
        } else if (*p < 0x20 && *p != '\t') {
            dst[d_idx++] = ' ';
        } else {
            dst[d_idx++] = (char)*p;
        }
    }
    dst[d_idx] = '\0';
}

// Validate identifier (table/column name)
static bool is_valid_ident(const char *s) {
    if (!s || !*s) return false;
    for (const char *p = s; *p; p++) {
        if (!isalnum((unsigned char)*p) && *p != '_') {
            return false;
        }
    }
    return true;
}

// Reset document attributes back to defaults for subsequent records
static void reset_doc_attrs(void) {
    sanitize_string_copy(g_doc_id, g_default_doc_id, sizeof(g_doc_id));
    sanitize_string_copy(g_lang, g_default_lang, sizeof(g_lang));
    sanitize_string_copy(g_category, g_default_category, sizeof(g_category));
}

// Emit dynamic DDL schema header
static void emit_schema_header(void) {
    printf("-- Auto-generated by UBS sql_filter (Injection-Safe Pipeline)\n");
    printf("PRAGMA journal_mode = WAL;\n");
    printf("PRAGMA synchronous = NORMAL;\n");
    printf("CREATE TABLE IF NOT EXISTS %s (\n", g_table_name);
    printf("    id INTEGER PRIMARY KEY AUTOINCREMENT");

    if (g_has_doc_id)     printf(",\n    %s TEXT", g_col_doc_id);
    if (g_has_lang)       printf(",\n    %s TEXT", g_col_lang);
    if (g_has_category)   printf(",\n    %s TEXT", g_col_category);
    if (g_has_raw_text)   printf(",\n    %s TEXT", g_col_raw_text);
    if (g_has_created_at) printf(",\n    %s DATETIME", g_col_created_at);

    printf("\n);\n");
}

// Emit dynamic INSERT record
static void emit_sql_record(const char *doc_id, const char *lang, const char *category, const char *raw_text) {
    if (g_insert_count % g_batch_size == 0) {
        printf("BEGIN TRANSACTION;\n");
    }

    printf("INSERT INTO %s (", g_table_name);
    bool first_col = true;
    if (g_has_doc_id) {
        printf("%s%s", first_col ? "" : ", ", g_col_doc_id);
        first_col = false;
    }
    if (g_has_lang) {
        printf("%s%s", first_col ? "" : ", ", g_col_lang);
        first_col = false;
    }
    if (g_has_category) {
        printf("%s%s", first_col ? "" : ", ", g_col_category);
        first_col = false;
    }
    if (g_has_raw_text) {
        printf("%s%s", first_col ? "" : ", ", g_col_raw_text);
        first_col = false;
    }
    if (g_has_created_at) {
        printf("%s%s", first_col ? "" : ", ", g_col_created_at);
        first_col = false;
    }
    printf(") VALUES (");

    bool first_val = true;
    if (g_has_doc_id) {
        if (!first_val) printf(", ");
        print_escaped_literal(doc_id);
        first_val = false;
    }
    if (g_has_lang) {
        if (!first_val) printf(", ");
        print_escaped_literal(lang);
        first_val = false;
    }
    if (g_has_category) {
        if (!first_val) printf(", ");
        print_escaped_literal(category);
        first_val = false;
    }
    if (g_has_raw_text) {
        if (!first_val) printf(", ");
        print_escaped_literal(raw_text);
        first_val = false;
    }
    if (g_has_created_at) {
        if (!first_val) printf(", ");
        printf("datetime('now')");
        first_val = false;
    }
    printf(");\n");

    g_insert_count++;
    if (g_insert_count % g_batch_size == 0) {
        printf("COMMIT;\n");
    }
}
%}

%union {
    char *str;
}

%token TOK_DOCUMENT TOK_ID TOK_LANG TOK_CATEGORY
%token <str> TOK_STRING_LITERAL TOK_RAW_TEXT TOK_RAW_LINE
%type <str> doc_body

%%

input_stream
    : document_list
    ;

document_list
    : /* empty */
    | document_list item
    ;

item
    : document
    | raw_line
    | error '\n'
      {
          yyerrok;
      }
    ;

document
    : TOK_DOCUMENT doc_header '{' doc_body '}'
      {
          emit_sql_record(g_doc_id, g_lang, g_category, $4);
          free($4);
          reset_doc_attrs();
      }
    ;

doc_header
    : /* empty */
    | '(' attr_list ')'
    ;

attr_list
    : attr
    | attr_list ',' attr
    ;

attr
    : TOK_ID ':' TOK_STRING_LITERAL
      {
          sanitize_string_copy(g_doc_id, $3, sizeof(g_doc_id));
          free($3);
      }
    | TOK_LANG ':' TOK_STRING_LITERAL
      {
          sanitize_string_copy(g_lang, $3, sizeof(g_lang));
          free($3);
      }
    | TOK_CATEGORY ':' TOK_STRING_LITERAL
      {
          sanitize_string_copy(g_category, $3, sizeof(g_category));
          free($3);
      }
    ;

doc_body
    : TOK_RAW_TEXT
      {
          $$ = $1;
      }
    ;

raw_line
    : TOK_RAW_LINE
      {
          emit_sql_record(g_doc_id, g_lang, g_category, $1);
          free($1);
      }
    ;

%%

void yyerror(const char *s) {
    (void)s;
}

static void print_help(const char *prog) {
    fprintf(stderr, "Usage: %s [options] < input_text\n\n", prog);
    fprintf(stderr, "Ultra-fast zero-ORM injection-safe text-to-SQLite stream filter.\n\n");
    fprintf(stderr, "General Options:\n");
    fprintf(stderr, "  -t, --table <name>          Destination table name (default: raw_corpus)\n");
    fprintf(stderr, "  -i, --doc_id <id>           Default doc_id for piped plain lines (default: anon_doc)\n");
    fprintf(stderr, "  -c, --category <name>       Default category attribute (default: general)\n");
    fprintf(stderr, "  -l, --lang <code>           Default lang attribute (default: ja)\n");
    fprintf(stderr, "  -b, --batch <size>          Batch transaction size (default: 1000)\n");
    fprintf(stderr, "  -w, --whole                 Ingest whole stdin stream as single record\n");
    fprintf(stderr, "  -h, --help                  Show this help message\n\n");
    fprintf(stderr, "Column Customization Options:\n");
    fprintf(stderr, "  --col-doc_id <name>         Rename doc_id column (default: doc_id)\n");
    fprintf(stderr, "  --col-lang <name>           Rename lang column (default: lang)\n");
    fprintf(stderr, "  --col-category <name>       Rename category column (default: category)\n");
    fprintf(stderr, "  --col-raw_text <name>       Rename raw_text column (default: raw_text)\n");
    fprintf(stderr, "  --col-created_at <name>     Rename created_at column (default: created_at)\n\n");
    fprintf(stderr, "Column Omission Flags:\n");
    fprintf(stderr, "  --no-doc_id                 Omit doc_id column from table and insert\n");
    fprintf(stderr, "  --no-lang                   Omit lang column from table and insert\n");
    fprintf(stderr, "  --no-category               Omit category column from table and insert\n");
    fprintf(stderr, "  --no-raw_text               Omit raw_text column from table and insert\n");
    fprintf(stderr, "  --no-created_at             Omit created_at column from table and insert\n");
}

typedef enum {
    LEX_TOP,
    LEX_HEADER,
    LEX_BODY
} LexState;

static LexState g_lex_state = LEX_TOP;
static StringBuffer line_buf = {NULL, 0, 0};

int yylex(void) {
    if (line_buf.cap == 0) {
        buf_init(&line_buf);
    }

    while (1) {
        if (g_lex_state == LEX_TOP) {
            line_buf.len = 0;
            if (line_buf.data) line_buf.data[0] = '\0';

            int c;
            while ((c = getchar()) != EOF) {
                buf_append_char(&line_buf, (char)c);
                if (c == '\n') break;
            }

            if (line_buf.len == 0 && c == EOF) {
                buf_free(&line_buf);
                return 0; // EOF
            }

            // Check if line is purely whitespace
            bool all_ws = true;
            for (size_t i = 0; i < line_buf.len; i++) {
                if (!isspace((unsigned char)line_buf.data[i])) {
                    all_ws = false;
                    break;
                }
            }
            if (all_ws) {
                continue; // Skip blank lines between documents
            }

            // Check if line starts a Document(...) or Document{ block
            char *p = line_buf.data;
            while (*p && isspace((unsigned char)*p)) p++;

            if (strncmp(p, "Document", 8) == 0 && (p[8] == '(' || p[8] == '{' || isspace((unsigned char)p[8]))) {
                p += 8;
                while (*p && isspace((unsigned char)*p)) p++;

                // Put back the rest of the line so header parsing can read it
                for (int i = (int)strlen(line_buf.data) - 1; i >= (int)(p - line_buf.data); i--) {
                    ungetc(line_buf.data[i], stdin);
                }

                g_lex_state = LEX_HEADER;
                return TOK_DOCUMENT;
            }

            // Strip trailing newlines for raw line insertion
            if (line_buf.len > 0 && line_buf.data[line_buf.len - 1] == '\n') {
                line_buf.data[--line_buf.len] = '\0';
            }
            if (line_buf.len > 0 && line_buf.data[line_buf.len - 1] == '\r') {
                line_buf.data[--line_buf.len] = '\0';
            }

            yylval.str = strdup(line_buf.data ? line_buf.data : "");
            return TOK_RAW_LINE;
        }

        if (g_lex_state == LEX_HEADER) {
            int c;
            while ((c = getchar()) != EOF && isspace(c)) {
                // skip whitespace
            }
            if (c == EOF) return 0;

            if (c == '(' || c == ')' || c == ',' || c == ':') {
                return c;
            }

            if (c == '{') {
                g_lex_state = LEX_BODY;
                g_text_buf.len = 0;
                if (g_text_buf.data) g_text_buf.data[0] = '\0';
                return '{';
            }

            if (c == '}') {
                g_lex_state = LEX_TOP;
                return '}';
            }

            if (c == '"') {
                StringBuffer val;
                buf_init(&val);
                while ((c = getchar()) != EOF && c != '"') {
                    if (c == '\\') {
                        int nc = getchar();
                        if (nc != EOF) {
                            c = nc;
                        } else {
                            break;
                        }
                    }
                    buf_append_char(&val, (char)c);
                }
                buf_append_char(&val, '\0');
                yylval.str = strdup(val.data ? val.data : "");
                buf_free(&val);
                return TOK_STRING_LITERAL;
            }

            if (isalpha(c) || c == '_') {
                StringBuffer id;
                buf_init(&id);
                buf_append_char(&id, (char)c);
                while ((c = getchar()) != EOF && (isalnum(c) || c == '_' || c == '-')) {
                    buf_append_char(&id, (char)c);
                }
                if (c != EOF) ungetc(c, stdin);
                buf_append_char(&id, '\0');

                if (strcmp(id.data, "id") == 0 || strcmp(id.data, "doc_id") == 0) {
                    buf_free(&id);
                    return TOK_ID;
                }
                if (strcmp(id.data, "lang") == 0) {
                    buf_free(&id);
                    return TOK_LANG;
                }
                if (strcmp(id.data, "category") == 0) {
                    buf_free(&id);
                    return TOK_CATEGORY;
                }

                yylval.str = strdup(id.data ? id.data : "");
                buf_free(&id);
                return TOK_RAW_TEXT;
            }

            return c;
        }

        if (g_lex_state == LEX_BODY) {
            int c;
            while ((c = getchar()) != EOF) {
                if (c == '\\') {
                    int next_c = getchar();
                    if (next_c == '}') {
                        buf_append_char(&g_text_buf, '}');
                        continue;
                    } else if (next_c != EOF) {
                        buf_append_char(&g_text_buf, '\\');
                        buf_append_char(&g_text_buf, (char)next_c);
                        continue;
                    }
                }
                if (c == '}') {
                    // Put back '}' so LEX_HEADER will emit it next to reduce the document
                    ungetc('}', stdin);
                    g_lex_state = LEX_HEADER;
                    if (g_text_buf.len == 0) {
                        buf_append_char(&g_text_buf, '\0');
                    }
                    yylval.str = strdup(g_text_buf.data ? g_text_buf.data : "");
                    return TOK_RAW_TEXT;
                }
                buf_append_char(&g_text_buf, (char)c);
            }

            g_lex_state = LEX_TOP;
            if (g_text_buf.len == 0) {
                buf_append_char(&g_text_buf, '\0');
            }
            yylval.str = strdup(g_text_buf.data ? g_text_buf.data : "");
            return TOK_RAW_TEXT;
        }
    }
}

int main(int argc, char **argv) {
    buf_init(&g_text_buf);

    static struct option long_options[] = {
        {"table",           required_argument, 0, 't'},
        {"doc_id",          required_argument, 0, 'i'},
        {"doc-id",          required_argument, 0, 'i'},
        {"id",              required_argument, 0, 'i'},
        {"category",        required_argument, 0, 'c'},
        {"lang",            required_argument, 0, 'l'},
        {"batch",           required_argument, 0, 'b'},
        {"whole",           no_argument,       0, 'w'},
        {"help",            no_argument,       0, 'h'},
        // Column custom naming
        {"col-doc_id",      required_argument, 0, 1001},
        {"col-doc-id",      required_argument, 0, 1001},
        {"col-lang",        required_argument, 0, 1002},
        {"col-category",    required_argument, 0, 1003},
        {"col-raw_text",    required_argument, 0, 1004},
        {"col-raw-text",    required_argument, 0, 1004},
        {"col-created_at",  required_argument, 0, 1005},
        {"col-created-at",  required_argument, 0, 1005},
        // Column omission
        {"no-doc_id",       no_argument,       0, 1010},
        {"no-doc-id",       no_argument,       0, 1010},
        {"no-lang",         no_argument,       0, 1011},
        {"no-category",     no_argument,       0, 1012},
        {"no-raw_text",     no_argument,       0, 1013},
        {"no-raw-text",     no_argument,       0, 1013},
        {"no-created_at",   no_argument,       0, 1014},
        {"no-created-at",   no_argument,       0, 1014},
        {0, 0, 0, 0}
    };

    int opt;
    int option_index = 0;
    while ((opt = getopt_long(argc, argv, "t:i:c:l:b:wh", long_options, &option_index)) != -1) {
        switch (opt) {
            case 't':
                if (is_valid_ident(optarg)) {
                    strncpy(g_table_name, optarg, sizeof(g_table_name) - 1);
                    g_table_name[sizeof(g_table_name) - 1] = '\0';
                } else {
                    fprintf(stderr, "Error: Invalid table identifier '%s'\n", optarg);
                    return 1;
                }
                break;
            case 'i':
                sanitize_string_copy(g_default_doc_id, optarg, sizeof(g_default_doc_id));
                sanitize_string_copy(g_doc_id, optarg, sizeof(g_doc_id));
                break;
            case 'c':
                sanitize_string_copy(g_default_category, optarg, sizeof(g_default_category));
                sanitize_string_copy(g_category, optarg, sizeof(g_category));
                break;
            case 'l':
                sanitize_string_copy(g_default_lang, optarg, sizeof(g_default_lang));
                sanitize_string_copy(g_lang, optarg, sizeof(g_lang));
                break;
            case 'b':
                g_batch_size = atol(optarg);
                if (g_batch_size <= 0) g_batch_size = 1000;
                break;
            case 'w':
                g_whole_mode = true;
                break;
            case 1001:
                if (is_valid_ident(optarg)) {
                    strncpy(g_col_doc_id, optarg, sizeof(g_col_doc_id) - 1);
                    g_col_doc_id[sizeof(g_col_doc_id) - 1] = '\0';
                }
                break;
            case 1002:
                if (is_valid_ident(optarg)) {
                    strncpy(g_col_lang, optarg, sizeof(g_col_lang) - 1);
                    g_col_lang[sizeof(g_col_lang) - 1] = '\0';
                }
                break;
            case 1003:
                if (is_valid_ident(optarg)) {
                    strncpy(g_col_category, optarg, sizeof(g_col_category) - 1);
                    g_col_category[sizeof(g_col_category) - 1] = '\0';
                }
                break;
            case 1004:
                if (is_valid_ident(optarg)) {
                    strncpy(g_col_raw_text, optarg, sizeof(g_col_raw_text) - 1);
                    g_col_raw_text[sizeof(g_col_raw_text) - 1] = '\0';
                }
                break;
            case 1005:
                if (is_valid_ident(optarg)) {
                    strncpy(g_col_created_at, optarg, sizeof(g_col_created_at) - 1);
                    g_col_created_at[sizeof(g_col_created_at) - 1] = '\0';
                }
                break;
            case 1010: g_has_doc_id = false; break;
            case 1011: g_has_lang = false; break;
            case 1012: g_has_category = false; break;
            case 1013: g_has_raw_text = false; break;
            case 1014: g_has_created_at = false; break;
            case 'h':
                print_help(argv[0]);
                return 0;
            default:
                print_help(argv[0]);
                return 1;
        }
    }

    emit_schema_header();

    if (g_whole_mode) {
        int c;
        while ((c = getchar()) != EOF) {
            buf_append_char(&g_text_buf, (char)c);
        }
        if (g_text_buf.len > 0) {
            emit_sql_record(g_doc_id, g_lang, g_category, g_text_buf.data);
        }
    } else {
        yyparse();
    }

    if (g_insert_count % g_batch_size != 0) {
        printf("COMMIT;\n");
    }

    fprintf(stderr, "[*] Successfully processed %ld document(s) into SQL stream.\n", g_insert_count);

    buf_free(&g_text_buf);
    buf_free(&line_buf);
    return 0;
}